repo: "responsive-header"
canvasCourse: "467502"
canvasAssignment: "4177784"

naming: true
commits: 2
liveWebsite: true

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['html', 'text-size-adjust', '100%']
      - ['html', '-moz-text-size-adjust', '100%']
      - ['html', '-ms-text-size-adjust', '100%']
      - ['html', '-webkit-text-size-adjust', '100%']
      - ['html', 'font', 'normal 100%/1.3 Ubuntu, sans-serif']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', '0']
      - ['header', 'background-color', '#18294f']
      - ['header', 'color', '#fff']
      - ['header h1']
      - ['nav ul', 'font-size', '1.125rem']
      - ['nav a', 'white-space', 'nowrap']
      - ['nav a:hover', 'background-color', '#6c8fe0']
      - ['nav a:hover', 'color', '#fff']
    search:
      - '@-moz-viewport'
      - '@-ms-viewport'
      - '@-o-viewport'
      - '@-webkit-viewport'
      - '@viewport'
      - '@media only screen and \(min-width: 25em\) \{'
      - '@media only screen and \(min-width: 38em\) \{'
      - '@media only screen and \(min-width: 60em\) \{'
      - '@media only screen and \(min-width: 90em\) \{'
      - 'font\-size\: 110%'
      - 'font\-size\: 120%'
      - 'font\-size\: 130%'
      - 'line\-height\: 1\.4'
      - 'line\-height\: 1\.5'
      - 'float\: left'
      - 'float\: right'
      - 'overflow\: hidden'
      - 'width\: 50\%'
      - 'width\: 25\%'
    search_not:
      - ['@media.+\(.*max-width', 'Media queries with `max-width` should not be used — use `min-width` instead']
      - ['@media.+\(.*px', 'Pixel units should not be used in media queries — use `em` instead']
      - ['font-size\s*:\s*.+px', 'Pixel units should not be used for `font-size` — use `rem` instead']
      - ['line-height\s*:\s*.+(px|rem|em)', 'Line heights should not have units']

screenshots:
  - path: "index.html"
    sizes: [320, 400, 650, 980, 1400]
